require('bootstrap');
require('jquery');
require('owl.carousel');
require('select2');
require('lightbox2');
require('jquery-aniview');
require('./animatescroll');
require('./script');
require('./script2');
